import { Elysia } from "elysia";
import { osuOAuthStateStore } from "../auth";
import { serverIdentity } from "../identity";
import { createOsuAuthorizationUrl, getOsuAuthorizationConfiguration } from "../osu-authorization";
import { logSafeFailure } from "../security/http";

export const authRoute = new Elysia().get("/auth", async ({ request, set }) => {
    set.headers["Cache-Control"] = "no-store";
    const identity = await serverIdentity.getCurrent(request.headers);

    if (!identity) {
        set.status = 401;
        return { error: "Unauthorized" };
    }

    if (new URL(request.url).searchParams.size > 0) {
        set.status = 400;
        return { error: "OAuth state is generated by the server" };
    }

    const osuConfiguration = getOsuAuthorizationConfiguration();
    if (!osuConfiguration) {
        console.error("Missing required environment variables for osu! auth");
        set.status = 500;
        return { error: "Server configuration error" };
    }

    try {
        const osuAuthUrl = await createOsuAuthorizationUrl(osuOAuthStateStore, identity, osuConfiguration);
        return { url: osuAuthUrl };
    } catch (error) {
        logSafeFailure("start osu! authorization", error);
        set.status = 500;
        return { error: "The osu! authorization could not be started" };
    }
});
